export enum Title {
  FIRST='giai doan phat am',
  SECOND='giai doan ngu phap',
  THIRD='giai doan giai de (test 1)',
  FOURTH='giai doan giai de (test 2)',
  FIFTH='giai doan giai de (test 3)',
  SIXTH='giai doan giai de (test 4)',
  SEVENTH='giai doan giai de (test 5)',
  EIGHTH='giai doan giai de (test 6)',
  NINTH='giai doan giai de (test 7)',
  TENTH='giai doan giai de (test 8)',
  ELEVENTH='giai doan giai de (test 9)',
  TWELFTH='giai doan giai de (test 10)',
  THIRTEENTH='Bo ETS 2019 test 1',
  FOURTEENTH='Bo ETS 2019 test 2',
  FIFTEENTH='Bo ETS 2023 test 1',
  SIXTEENTH='Bo ETS 2023 test 2',
  SEVENTEENTH='Bo ETS 2023 test 3',
  EIGHTEENTH='Bo ETS 2023 test 4',
  NINETEENTH='Bo ETS 2023 test 5',
  TWENTIETH='Bo ETS 2023 test 8',
}